project:
  output-dir: ./docs/en

book:
  title: "Philosophy of Science"
  navbar:
    background: primary
    left:
    - text: "About"
      href: about-en.html 
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html  
  chapters:
    - index.qmd
    - about-en.qmd
    - part: "Mathematics"
      chapters:
        - course-contents/output-en.md
    - part: "Statistics"
      chapters:        
        - course-contents/databases-intro-en.qmd
        - course-contents/database-models-en.qmd

    - part: "Causality"
      chapters:
        - course-contents/er-model-en.qmd
        - course-contents/er-model-mermaid-diagrams-en.qmd
    - references-en.qmd
