
::: {.content-visible when-profile="def"}
# Preface (Önsöz) {.unnumbered} 

- [Thoughts on Philosophy of Science (English)](./en/index.html)

- [Bilim Felsefesi üzerine düsünceler (Türkçe)](./tr/index.html)

:::

::: {.content-visible when-profile="en"}
# Content  {.numbered} 

This site aims to create an interdisciplinary space of thought that brings together philosophy of science and mathematical reasoning. It is important that the content maintains a certain academic standard while also being accessible to a broad audience.


This site will feature discussions on

- Philosophy of science
- The use of language (formal, and natural) in sciences
- Mathematics
- The use of mathematics in sciences
- The Islamic philosophy    

:::



::: {.content-visible when-profile="tr"}
# İçerik  {.numbered} 

Bu site, bilim felsefesi ve matematiksel dusunce bir araya getiren disiplinler arası bir düşünce alanı oluşturmayı amaçlamaktadır. İçeriklerin, hem belli bir akademik seviyeyi korumasi, hem de geniş bir kitle tarafından anlaşılabilir nitelikte bulunması önemlidir.


Sitede odaklanılacak konular genel olarak:

- Bilim felsefesi
- Bilimsel yöntemde dilin (doğal ve formal) rolü
- Matematik
- Matematiğin bilimlerdeki rolü
- İslami felsefe

:::

::: {.content-visible when-profile="en"}
# Contact  {.numbered} 

To send your comments or to contribute to this website with content, 

email: thoughts.and.discourse@gmail.com

:::


::: {.content-visible when-profile="tr"}
# İletişim  {.numbered} 

Yorumlarla veya siteye içerik olarak katkıda bulunmak için

email: thoughts.and.discourse@gmail.com

:::








